### ISSUE TITLE
Any thoughts on the new banners/screenshots?

### ISSUE THREAD

**Issue by andreaslarsen** [andreaslarsen/monoid#14]
![image](https://github.com/andreaslarsen/mono16/blob/master/Images/Monoid1.png?raw=true)
![image](https://github.com/andreaslarsen/mono16/blob/master/Images/Monoid2.png?raw=true)
![image](https://github.com/andreaslarsen/mono16/blob/master/Images/Monoid3.png?raw=true)
![image](https://github.com/andreaslarsen/mono16/blob/master/Images/Monoid4.png?raw=true)
![image](https://github.com/andreaslarsen/mono16/blob/master/Images/Monoid5.png?raw=true)

**Comment by chase** [comment]
They aren't as descriptive as the old README, in my opinion.
Perhaps decrease the height and then put an explanation below each banner?

**Comment by andreaslarsen** [comment]
They aren't intended to replace the readme - I moved the content from the readme to the webpage to have all info in one place. I just updated the readme to make that clearer.

I made them for websites/blogs to use when posting about it.

**Comment by andreaslarsen** [comment]
Just finished updating the readme with custom banner + new content
