### ISSUE TITLE
CircleCI Doesn't Seem to Modify Release Branch?

### ISSUE THREAD

**Issue by chase** [andreaslarsen/monoid#18]
Have you signed up with CircleCI? It doesn't seem to be working, but I can't tell if it is failing if you don't let me know or figure out a solution. It *was* working for me, but I don't have the ability to test it on this repo as a collaborator.

**Comment by andreaslarsen** [comment]
I haven't signed up yet, no. Will do it later tonight and report back if I have any issues :)

**Comment by andreaslarsen** [comment]
holy fuckballs that was the most streamlined signup process I have ever tried - it seems to be building away just fine right now,

**Comment by andreaslarsen** [comment]
Wow, it's already done, looks and works amazing!

**Comment by andreaslarsen** [comment]
It runs every time I commit something to the master branch, right?

**Comment by andreaslarsen** [comment]
I can see it does, is that "ok"?

**Comment by chase** [comment]
That is what it is supposed to do. Later on I'll make it so that build only runs if the source files are different from the last release.

**Comment by andreaslarsen** [comment]
perfect, no rush adjusting that but when you do maybe also make it so it empties the releases folder before adding the updated files.

**Comment by chase** [comment]
I was just thinking about that myself. It's definitely on the todo list.

**Comment by chase** [comment]
Can you go on CircleCI and check if there is an error message?

**Comment by andreaslarsen** [comment]
Looks more like circleCI isn't initiated at all 
![screen shot 2015-05-26 at 09 02 38](https://cloud.githubusercontent.com/assets/3859425/7806862/15cba400-0386-11e5-8450-96c23979524e.png)
![screen shot 2015-05-26 at 09 02 12](https://cloud.githubusercontent.com/assets/3859425/7806863/15ec9034-0386-11e5-995e-ff0ae0f9246c.png)

**Comment by chase** [comment]
Huh, makes me think that maybe the Github hook for it got broken at some point.

**Comment by andreaslarsen** [comment]
I feel like I'm missing something very obvious but how does one remove it?

**Comment by chase** [comment]
Huh, well I guess you can't, you can only "unfollow" it, which seems to have been done for you accidentally. Time to contact CircleCI's support, haha. Just click the little help bubble in the bottom right corner and make a new message explaining this issue.

**Comment by andreaslarsen** [comment]
yep, just did that, waiting for reply :)

**Comment by andreaslarsen** [comment]
up an running again - I just had to re add it as service here - not sure why it "disappeared" in the first place though :+1:
