### ISSUE TITLE
Please add the Ə letter

### ISSUE THREAD

**Issue by Tural** [andreaslarsen/monoid#21]

**Comment by andreaslarsen** [comment]
![screen shot 2015-05-25 at 13 28 36](https://cloud.githubusercontent.com/assets/3859425/7796667/f830f1b0-02e1-11e5-94c6-cd97ed92fbd5.png)

It is uploading/building now so it takes 10 min or so before it's done

**Comment by Tural** [comment]
thanks so much

**Comment by andreaslarsen** [comment]
No problem, looks like it isn't CircleCI isn't running though so might take a little longer - have we changed anything in the setup @chase?

**Comment by chase** [comment]
Only things I tested, but I'll look into this after work today.

**Comment by andreaslarsen** [comment]
Great!...I always forget you're on a different time zone - it's 19:30 and holiday here :)

**Comment by Tural** [comment]
I have tried to download it for several time, and controled it but it hasn`t change.  Capital Ə is invisible. maybe it is because of the github that haven`t update yet.

**Comment by chase** [comment]
@Tural, our release system seems to be down at the moment, so the download will not be available. I apologize for the inconvenience. I'll have it ready to go as soon as possible.

**Comment by andreaslarsen** [comment]
@Tural should work now :+1:

**Comment by Tural** [comment]
@andreaslarsen  please, send it to my mail. (turalalisoy@gmail.com) because I have downloaded it and not working.

**Comment by andreaslarsen** [comment]
What's not working? I just tried downloading one of them and it looked fine. I "only" have what's online - the CI builds the font when I update the source - you can browse them manually on https://github.com/andreaslarsen/monoid/tree/release (~1600 variants due to the different combinations)

**Comment by Tural** [comment]
@andreaslarsen I was downloading from this link. http://andreaslarsen.github.io/monoid/  Entered to the link you gave me and downloaded firt .zip file and  Ə letter cannot reading. And I have meet with this error: 
Sorry, we had to truncate this directory to 1,000 files. 601 entries were omitted from the list.

**Comment by chase** [comment]
@Tural, could you tell me which configuration options you chose on the website?

The default with no options does contain U+018F (Ə):
https://cdn.rawgit.com/andreaslarsen/monoid/release/Monoid.ttf.zip

If this contains the character Ə for you, but the one you configure does not, please let me know.

**Comment by Tural** [comment]
@chase I am using mac os. is that possible mac  os not supperting it? but I`m not sure about that. cuz little e is reading the problem is big E, it looks like square and not reading. from that link I`m downloading  https://github.com/andreaslarsen/monoid/tree/release but still the same.

**Comment by andreaslarsen** [comment]
@tural try open Font Book and inspect the font.

![screen shot 2015-05-28 at 14 59 51](https://cloud.githubusercontent.com/assets/3859425/7860537/3fbcf884-054a-11e5-81d0-f5f5bc8e1310.png)

**Comment by Tural** [comment]
there is only little ə in font book. I am showing that as photoshop simple. All of them are monoid font and besides big Ə
![untitled-1](https://cloud.githubusercontent.com/assets/518994/7861370/1d9afec6-0569-11e5-946d-461b2dcf9201.jpg)

**Comment by andreaslarsen** [comment]
so you don't have the character between long-s and capital-o-ogonek as shown in my fontbook?

**Comment by andreaslarsen** [comment]
Works fine in photoshop
![screen shot 2015-05-28 at 16 01 57](https://cloud.githubusercontent.com/assets/3859425/7861862/e868f53e-0552-11e5-8cb7-1ddc6623f0d6.png)

**Comment by Tural** [comment]
unfortunately, no

**Comment by larsenwork** [comment]
hmm...did you remember to delete the old monoid before installing the new one?

**Comment by Tural** [comment]
yes. could you please send me the original version of this from your laptop before downloading there? this time I would like to try it like this. my mail turalalisoy@gmail.com

**Comment by larsenwork** [comment]
There's still no "original version" - unless you mean the .sfdir source file here in the repo? You need FontForge to open that.
The one I have on my computer I downloaded from the website yesterday: https://dl.dropboxusercontent.com/u/3019777/Monoid-a3.ttf = 
https://github.com/larsenwork/monoid/blob/release/Monoid-a3.ttf.zip

**Comment by Tural** [comment]
finally worked =) so so thanks

**Comment by Tural** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/518994/7863100/b528631e-0573-11e5-87b1-8d0147e003aa.jpg)

**Comment by larsenwork** [comment]
Cheers, you must've been doing something funky earlier but glad it works for you now. Remember to share the font with others if you enjoyed it :wink:

**Comment by Tural** [comment]
Thank you very much for your help. Please, next time when you are going to create new fonts, dont forget about Azerbaijan alphabet. The letters: Əə Ğğ İı Üü Öö Çç Şş =)

**Comment by larsenwork** [comment]
I've also made [gidole](http://gidole.github.io) - I actually think it has all those too but not sure. Coming from a small country with special characters myself (æøå) so always fun to add in other languages too.

**Comment by Tural** [comment]
It is working, I have tried.

**Comment by larsenwork** [comment]
cheers
