### ISSUE TITLE
Website to-do

### ISSUE THREAD

**Issue by andreaslarsen** [andreaslarsen/monoid#9]
- [x] Implement advanced downloads once #2 is complete
- [x] Code samples in other languages (e.g. Russian, Spanish or other...help)

Other ideas?

**Comment by chase** [comment]
Regarding the code samples, since you are already using Prism for syntax highlighting, you could likely use their samples:
https://github.com/PrismJS/prism/tree/master/examples

**Comment by andreaslarsen** [comment]
Hehe, I should have been more specific...what I thought about was code in e.g. Russian/with Russian comments, or Czech, or Latvian etc. :smile:

**Comment by andreaslarsen** [comment]
The website is now ready.
